from unittest import result

from reportlab.lib import styles
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
from pathlib import Path
from datetime import datetime


def generate_pdf_report(features, result):

    output_folder = Path("generated_reports")
    output_folder.mkdir(exist_ok=True)

    filename = f"assessment_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    pdf_path = output_folder / filename

    doc = SimpleDocTemplate(str(pdf_path))

    styles = getSampleStyleSheet()

    story = []

    # --------------------------------------------------

    story.append(Paragraph("<b>AI Pediatric Malnutrition Detection Report</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            f"Assessment Date: {datetime.now().strftime('%d %B %Y %H:%M')}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(Paragraph("<b>Child Information</b>", styles["Heading2"]))

    story.append(Paragraph(f"Age: {features['age_months']} months", styles["BodyText"]))
    story.append(
        Paragraph(
            f"Sex: {'Male' if features['sex']==1 else 'Female'}",
            styles["BodyText"]
        )
    )
    story.append(Paragraph(f"Weight: {features['weight_kg']} kg", styles["BodyText"]))
    story.append(Paragraph(f"Height: {features['height_cm']} cm", styles["BodyText"]))
    story.append(Paragraph(f"MUAC: {features['muac_cm']} cm", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(Paragraph("<b>Prediction Results</b>", styles["Heading2"]))

    prediction = result["Prediction"]

    story.append(
        Paragraph(
            f"Underweight: {'Detected' if prediction['Underweight'] else 'Not Detected'}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Stunting: {'Detected' if prediction['Stunting'] else 'Not Detected'}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Wasting: {'Detected' if prediction['Wasting'] else 'Not Detected'}",
            styles["BodyText"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    # --------------------------------------------------

    story.append(Paragraph("<b>Assessment</b>", styles["Heading2"]))

    assessment = result["Assessment"]

    for key, value in assessment.items():
        story.append(
            Paragraph(f"{key}: {value}", styles["BodyText"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------
    # --------------------------------------------------

    story.append(Paragraph("<b>Recommendations</b>", styles["Heading2"]))

    for item in result["Recommendations"]:
        story.append(
            Paragraph("• " + item, styles["BodyText"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(Paragraph("<b>Medical Alerts</b>", styles["Heading2"]))

    if result["Alerts"]:

        for alert in result["Alerts"]:
            story.append(
                Paragraph("• " + alert, styles["BodyText"])
            )

    else:

        story.append(
            Paragraph("No medical alerts.", styles["BodyText"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(
        Paragraph(
            "<b>Generated by AI Pediatric Malnutrition Detection System</b>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return pdf_path