from reportlab.lib import styles
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph
from pathlib import Path
from datetime import datetime
from reportlab.lib import colors


def generate_pdf_report(features, result):

    PROJECT_ROOT = Path(__file__).resolve().parents[2]

    output_folder = PROJECT_ROOT / "generated_reports"

    output_folder.mkdir(exist_ok=True)    
    
    filename = f"assessment_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    pdf_path = output_folder / filename

    doc = SimpleDocTemplate(str(pdf_path))

    styles = getSampleStyleSheet()

    title_style = styles["Title"]

    heading_style = styles["Heading2"]

    heading_style.textColor = colors.darkblue

    body_style = styles["BodyText"]

    body_style.leading = 18

    story = []

    # --------------------------------------------------

    story.append(Paragraph("<b>AI Pediatric Malnutrition Detection Report</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            f"Assessment Date: {datetime.now().strftime('%d %B %Y %H:%M')}",
            styles["Normal"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(Paragraph("<b>Child Information</b>", styles["Heading2"]))

    story.append(Paragraph(f"Age: {features['age_months']} months", styles["BodyText"]))
    story.append(
        Paragraph(
            f"Sex: {'Male' if features['sex']==1 else 'Female'}",
            styles["BodyText"]
        )
    )
    story.append(Paragraph(f"Weight: {features['weight_kg']} kg", styles["BodyText"]))
    story.append(Paragraph(f"Height: {features['height_cm']} cm", styles["BodyText"]))
    story.append(Paragraph(f"MUAC: {features['muac_cm']} cm", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(
        Paragraph(
            "<font color='darkblue'><b>AI Prediction Results</b></font>",
            heading_style
        )
    )
    prediction = result["Prediction"]



    story.append(
        Paragraph(
            f"Underweight: {'Detected' if prediction['Underweight'] else 'Not Detected'}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Stunting: {'Detected' if prediction['Stunting'] else 'Not Detected'}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Wasting: {'Detected' if prediction['Wasting'] else 'Not Detected'}",
            styles["BodyText"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    # --------------------------------------------------

    story.append(
        Paragraph(
            "<font color='darkblue'><b>Clinical Assessment</b></font>",
            heading_style
        )
    )
    assessment = result["Assessment"]

    for key, value in assessment.items():
        story.append(
            Paragraph(f"{key}: {value}", styles["BodyText"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------
    # --------------------------------------------------

    story.append(
        Paragraph(
            "<font color='darkblue'><b>Recommendations</b></font>",
            heading_style
        )
    )

    for item in result["Recommendations"]:
        story.append(
            Paragraph("• " + item, styles["BodyText"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "<font color='darkblue'><b>Food Recommendations</b></font>",
            heading_style
        )
    )

    foods = result["Food Recommendations"]

    for category, items in foods.items():

        story.append(
            Paragraph(f"<b>{category}</b>", body_style)
        )

        for item in items:
            story.append(
                Paragraph("• " + item, body_style)
            )

        story.append(Paragraph("<br/>", styles["Normal"]))


    # --------------------------------------------------

    story.append(
        Paragraph(  
            "<font color='darkblue'><b>Medical Alerts</b></font>",
            heading_style
        )
    )

    if result["Alerts"]:

        for alert in result["Alerts"]:
            story.append(
                Paragraph("• " + alert, styles["BodyText"])
            )

    else:

        story.append(
            Paragraph("No medical alerts.", styles["BodyText"])
        )

    story.append(Paragraph("<br/>", styles["Normal"]))

    # --------------------------------------------------

    story.append(
        Paragraph(
            "<b>Generated by AI Pediatric Malnutrition Detection System</b>",
            styles["Italic"]
        )
    )

    story.append(
        Paragraph(
            "<font color='darkblue'><b>Clinical Summary</b></font>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            result["Clinical Summary"],
            body_style
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))



    # --------------------------------------------------


    story.append(Paragraph("<b>WHO Growth Assessment</b>", styles["Heading2"]))

    growth = result["WHO Growth"]

    story.append(Paragraph(f"WAZ: {growth['waz']:.2f}", styles["BodyText"]))
    story.append(Paragraph(f"WAZ Status: {growth['waz_status']}", styles["BodyText"]))

    story.append(Paragraph(f"HAZ: {growth['haz']:.2f}", styles["BodyText"]))
    story.append(Paragraph(f"HAZ Status: {growth['haz_status']}", styles["BodyText"]))

    story.append(Paragraph(f"WHZ: {growth['whz']:.2f}", styles["BodyText"]))
    story.append(Paragraph(f"WHZ Status: {growth['whz_status']}", styles["BodyText"]))

    story.append(Paragraph(f"BMI: {growth['bmi']:.2f}", styles["BodyText"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

# --------------------------------------------------
    doc.build(story)

    return pdf_path
